project_name: WHHA
builds:
  - env: [ CGO_ENABLED=0 ]
    goos:
      - linux
      - windows
      - darwin
checksum:
  name_template: 'checksums.txt'
archives:
  - replacements:
      linux: Linux
      windows: Windows
      darwin: MacOs
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - config.yaml